kind: pipeline
name: default

services:
- name: db
  image: mysql:8.0.18
  build_args:
  - --default-authentication-plugin=mysql_native_password
  environment:
    MYSQL_ROOT_PASSWORD: abcd
    MYSQL_DATABASE: test
steps:
- name: integration-test
  image: dhoer/flyway:alpine
  commands:
    - sleep 20
    - flyway -user=root -password=abcd -url=jdbc:mysql://db:3306/test -schemas=test -locations=filesystem:sql -connectRetries=40 migrate
- name: deploy
  image: rubasace/flyway-port-forward
  environment:
    K8S_CERT_AUTHORITY_DATA:
      from_secret: K8S_CERT_AUTHORITY_DATA
    K8S_SERVER:
      from_secret: K8S_SERVER
    K8S_USER:
      from_secret: K8S_USER
    K8S_PASSWORD:
      from_secret: K8S_PASSWORD
    DB_USER:
      from_secret: DB_USER
    DB_PASSWORD:
      from_secret: DB_PASSWORD
    DB_ENGINE: mysql
    DB_NAME: vidaviajera
    DB_SVC: mysql
    DB_SVC_PORT: "3306"
    NAMESPACE: production
  when:
    branch:
    - master