kind: pipeline
name: default

steps:
- name: bake
  image: plugins/docker
  settings:
    username:
      from_secret: docker_user
    password:
      from_secret: docker_pass
    repo: registry.anieto.dev/v2/adrian/vida-viajera-db
    registry: registry.anieto.dev/v2
    tags: 1.0.0.${CI_BUILD_NUMBER}
  when:
    branch:
    - master
- name: deploy
  image: rubasace/drone-k8s
  environment:
    K8S_CERT_AUTHORITY_DATA:
      from_secret: K8S_CERT_AUTHORITY_DATA
    K8S_SERVER:
      from_secret: K8S_SERVER
    K8S_USER:
      from_secret: K8S_USER
    K8S_PASSWORD:
      from_secret: K8S_PASSWORD
    DB_URL: jdbc:mysql://mysql.production:3306/
    DB_NAME: vidaviajera
  commands:
    # TODO: put scripts inside env folder
    - kubectl run flyway-migrator-`uuidgen` --rm -it --image=registry.anieto.dev/v2/adrian/vida-viajera-db:1.0.0.${CI_BUILD_NUMBER} --restart=Never -- -baselineOnMigrate=true -baselineVersion=1.2 -url=${DB_URL} -schemas=${DB_NAME} -user=${DB_USER} -password=${DB_PASSWORD} -locations=filesystem:/sql/schema,filesystem:/sql/data/${ENVIRONMENT} migrate