kind: pipeline
name: default

steps:
- name: deploy
  image: rubasace/flyway-port-forward
  environment:
    K8S_CERT_AUTHORITY_DATA:
      from_secret: K8S_CERT_AUTHORITY_DATA
    K8S_SERVER:
      from_secret: K8S_SERVER
    K8S_USER:
      from_secret: K8S_USER
    K8S_PASSWORD:
      from_secret: K8S_PASSWORD
    DB_NAME: vidaviajera
    DB_SVC: mysql
    DB_SVC_PORT: "3306"
    NAMESPACE: production
  build_args:
  - -baselineOnMigrate=true
  - -baselineVersion=1.4
  - -url=jdbc:mysql://localhost:8080/
  - -schemas="${DB_NAME}"
  - -locations=filesystem:sql
  - migrate
  when:
    branch:
    - master