CREATE TABLE User (
	id INT PRIMARY KEY AUTO_INCREMENT,
	username VARCHAR(50) NOT NULL
);

CREATE TABLE Reason (
	id INT PRIMARY KEY,
	description VARCHAR(100) NOT NULL
);

CREATE TABLE Trip (
	id INT PRIMARY KEY AUTO_INCREMENT,
	userId INT NOT NULL,
	reasonId INT NOT NULL,
	origin VARCHAR(50) NOT NULL,
	destination VARCHAR(50) NOT NULL,
	startDate DATE NOT NULL,
	endDate DATE NOT NULL,
    CONSTRAINT FK_UserId FOREIGN KEY (userId) REFERENCES User(id),
    CONSTRAINT FK_ReasonId FOREIGN KEY (reasonId) REFERENCES Reason(id)
);
